### ISSUE TITLE
taskdef class scala.tools.ant.Scalac cannot be found  using the classloader AntClassLoader

### ISSUE THREAD

**Issue by runtimee** [smartiniOnGitHub/grails-scala#4]
I have a pure (no scala) Grails project, branch _master_. While my feature branch _ScalaBus_ the scala plugin was introduced for the first time `compile ":scala:2.10.4"`, and everything worked fine.

However, when I switched back to master, it does not compile anymore, with error message:

```
| Error Error executing script Compile: : taskdef class scala.tools.ant.Scalac cannot be found
 using the classloader AntClassLoader[....
two-pages-of-full-path-jar-files:
... e.g.
.grails/ivy-cache/com.google.guava/guava-jdk5/jars/guava-jdk5-13.0.jar
...] (Use --stacktrace to see the full trace)
```

This can be manually fixed by deleting the scala folder under `~/.grails/VERSION/project/APP/plugins/scala-2.10.4`

What's the reason and what's the solution to this problem?

**Comment by smartiniOnGitHub** [comment]
Hi, probably this is due to differences in dependencies in your branches, while files are downloaded in a common .grails folder, so the need to a manual cleanup (I see this behavior many times even with other plugins because it's a default behavior in Grails). As a workaround you could set a different target folder in your webapps, as seen here:
https://github.com/smartiniOnGitHub/grails-scala/blob/master/test/webapp/grails-scala-test24/grails-app/conf/BuildConfig.groovy
in detail, there you can see this:
grails.project.class.dir = "target/classes"
grails.project.test.class.dir = "target/test-classes"
grails.project.test.reports.dir = "target/test-reports"
grails.project.work.dir = "target/work"
so I explicitly set to put everything inside the webapp target folder, so a clean-all or even a manual remove solve it.

Tell me if this is enough, otherwise if you have a minimal project to test it would be great.
Thanks, Sandro

**Comment by smartiniOnGitHub** [comment]
Closing because no further info is provided (I think all is resolved).
